#!/bin/sh

dir=$(dirname $(readlink -f $0))

if [ -z $VIRTUAL_ENV ]; then
	python=$dir/.virtualenv/bin/python
else
	python=python
fi

export PYTHONPATH=${PYTHONPATH}:$dir/

if [ "$1" = "test" ] || [ "$1" = "tests" ] || [ "$1" = "-t" ]; then
	if [ ! -f $dir/config.py ]; then
		cp $dir/config.example.py $dir/config.py
	fi
	pytest
	exit $?
fi

$python -m qdb
exit $?
